slackBotToken: xoxb-2070788189600-5625372662487-YA61hHFqPluXjVcJyG96SLFx

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: root
    password: root1234!
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug