spring:
  datasource:
    #    url: jdbc:mysql://localhost:3306/GOATODO?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url:
    username: root
    password: root1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true